'use client'

import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'vi'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    
    // Hero
    'hero.badge': 'Trusted by 100+ Businesses',
    'hero.title': 'Modern Web Solutions for',
    'hero.titleHighlight': 'Your Business',
    'hero.description': 'We create stunning websites, powerful web applications, and premium digital products. From React to Next.js, we bring your digital vision to life.',
    'hero.cta1': 'Start Your Project',
    'hero.cta2': 'View Our Work',
    'hero.stat1': 'Projects Completed',
    'hero.stat2': 'Years Experience',
    'hero.stat3': 'Client Rating',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive digital solutions to help your business grow and succeed online',
    'services.viewAll': 'View All Services',
    'service.webDev': 'Web Development',
    'service.webDevDesc': 'Custom websites built with modern technologies for optimal performance.',
    'service.uiux': 'UI/UX Design',
    'service.uiuxDesc': 'Beautiful, intuitive interfaces that provide exceptional user experiences and drive engagement.',
    'service.ecommerce': 'E-commerce Solutions',
    'service.ecommerceDesc': 'Complete online stores with secure payments, inventory management, and seamless checkout experiences.',
    'service.backend': 'Backend Development',
    'service.backendDesc': 'Robust server-side solutions with databases, APIs, and scalable architecture for your applications.',
    'service.responsive': 'Responsive Design',
    'service.responsiveDesc': 'Mobile-first designs that look perfect on all devices, from smartphones to desktop computers.',
    'service.seo': 'SEO Optimization',
    'service.seoDesc': 'Search engine optimization to improve your visibility and drive organic traffic to your website.',
    
    // Projects
    'projects.title': 'Featured Projects',
    'projects.subtitle': 'Explore our portfolio of successful projects delivered for clients worldwide',
    'projects.viewAll': 'View All Projects',
    
    // Testimonials
    'testimonials.title': 'Client Testimonials',
    'testimonials.subtitle': 'Hear from businesses that trusted us to bring their digital vision to life',
    'testimonial1.name': 'Sarah Johnson',
    'testimonial1.role': 'CEO, TechStart Inc',
    'testimonial1.content': 'Working with Wren Tech was an absolute pleasure. They delivered our e-commerce platform ahead of schedule with exceptional quality. The attention to detail and communication throughout the project was outstanding.',
    'testimonial2.name': 'Michael Chen',
    'testimonial2.role': 'Founder, CloudSolutions',
    'testimonial2.content': 'The team transformed our outdated website into a modern, high-performing application. Our conversion rate increased by 150% within the first month. Highly recommended for any business looking to scale.',
    'testimonial3.name': 'Emily Rodriguez',
    'testimonial3.role': 'Marketing Director, GrowthLab',
    'testimonial3.content': 'What impressed me most was their ability to understand our business needs and translate them into a beautiful, functional website. The project was completed on time and within budget.',
    'testimonial4.name': 'David Park',
    'testimonial4.role': 'Owner, Urban Bistro',
    'testimonial4.content': 'Our restaurant booking system has been a game-changer. Customers love the easy-to-use interface, and we\'ve seen a significant increase in reservations. The team went above and beyond.',
    'testimonial5.name': 'Lisa Thompson',
    'testimonial5.role': 'Freelance Designer',
    'testimonial5.content': 'As a freelancer, I needed a portfolio that showcased my work professionally. Wren Tech created exactly what I envisioned and more. I\'ve received numerous compliments and new project inquiries.',
    'testimonial6.name': 'James Wilson',
    'testimonial6.role': 'Director, FitLife Gym',
    'testimonial6.content': 'The fitness app they developed for us has been incredibly successful. Members love tracking their progress, and it\'s helped us build a stronger community. Professional service from start to finish.',
    
    // CTA
    'cta.title': 'Ready to Build Something Amazing?',
    'cta.subtitle': "Let's discuss your project and create a digital solution that drives results for your business.",
    'cta.button1': 'Get Started Today',
    'cta.button2': 'Email Us',
    'cta.support': 'Support Available',
    'cta.satisfaction': 'Satisfaction Guaranteed',
    'cta.delivery': 'Project Delivery',
    
    // Footer
    'footer.description': 'Professional web development and technical solutions. Building modern websites and applications for businesses worldwide.',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.service1': 'Web Development',
    'footer.service2': 'React Applications',
    'footer.service3': 'E-commerce Solutions',
    'footer.service4': 'Digital Products',
    'footer.aboutUs': 'About Us',
    
    // Services Page
    'servicesPage.title': 'Our Services',
    'servicesPage.subtitle': 'Comprehensive digital solutions designed to help your business grow and succeed in the modern web',
    'servicesPage.cta.title': 'Ready to Get Started?',
    'servicesPage.cta.subtitle': "Let's discuss your project and create a solution tailored to your needs",
    'servicesPage.cta.button': 'Contact Us Today',
    'servicesPage.feature1': 'Custom Development',
    'servicesPage.feature2': 'Responsive Design',
    'servicesPage.feature3': 'Performance Optimization',
    'servicesPage.feature4': 'SEO-Friendly',
    'servicesPage.feature5': 'User Research',
    'servicesPage.feature6': 'Wireframing',
    'servicesPage.feature7': 'Prototyping',
    'servicesPage.feature8': 'Visual Design',
    'servicesPage.feature9': 'Shopping Cart',
    'servicesPage.feature10': 'Payment Integration',
    'servicesPage.feature11': 'Product Management',
    'servicesPage.feature12': 'Order Tracking',
    'servicesPage.feature13': 'API Development',
    'servicesPage.feature14': 'Database Design',
    'servicesPage.feature15': 'Authentication',
    'servicesPage.feature16': 'Cloud Integration',
    'servicesPage.feature17': 'Mobile-First',
    'servicesPage.feature18': 'Cross-Browser',
    'servicesPage.feature19': 'Progressive Web Apps',
    'servicesPage.feature20': 'Touch Optimized',
    'servicesPage.feature21': 'Keyword Research',
    'servicesPage.feature22': 'On-Page SEO',
    'servicesPage.feature23': 'Technical SEO',
    'servicesPage.feature24': 'Analytics',
    
    // Projects Page
    'projectsPage.title': 'Our Projects',
    'projectsPage.subtitle': 'Explore our portfolio of successful projects delivered for clients worldwide',
    'projectsPage.project7.title': 'Paradise Resort Website',
    'projectsPage.project7.category': 'Web Development',
    'projectsPage.project7.description': 'A modern, luxury resort website with booking system, room listings, interactive galleries, and dining information. Built with Next.js and Prisma for seamless user experience.',
    'projectsPage.project7.client': 'Paradise Resort',
    'projectsPage.project8.title': 'Fashion E-commerce Store',
    'projectsPage.project8.category': 'E-commerce',
    'projectsPage.project8.description': 'A modern fashion e-commerce platform with product catalog, wishlist, shopping cart, currency conversion, and product comparison features. Built with React, TypeScript, and Vite for optimal performance.',
    'projectsPage.project8.client': 'Fashion Boutique',
    'projectsPage.project9.title': 'Real Estate Platform',
    'projectsPage.project9.category': 'Web Application',
    'projectsPage.project9.description': 'A comprehensive real estate website with property listings, advanced search filters, interactive Mapbox maps, favorites system, and user authentication. Built with Next.js 14 and PostgreSQL for optimal performance.',
    'projectsPage.project9.client': 'Prime Properties',
    'projectsPage.project10.title': 'Urban Bistro - Restaurant Booking',
    'projectsPage.project10.category': 'Full-Stack Web Application',
    'projectsPage.project10.description': 'A full-stack restaurant booking system with real-time availability updates, menu management, table reservations, and automated email confirmations. Features Socket.io for live updates and Redis caching.',
    'projectsPage.project10.client': 'Urban Bistro',
    'projectsPage.project11.title': 'Car Dana - Auto Dealership',
    'projectsPage.project11.category': 'Business Website',
    'projectsPage.project11.description': 'A professional car dealership website featuring hero sliders, vehicle listings with pricing, special offers, news & events, customer gallery, testimonials, and contact forms. Fully responsive with smooth animations and floating action buttons.',
    'projectsPage.project11.client': 'Car Dana',
    'projectsPage.project12.title': 'Nha Khoa ABC - Dental Clinic',
    'projectsPage.project12.category': 'Healthcare Website',
    'projectsPage.project12.description': 'A professional dental clinic website featuring service listings, doctor profiles, transparent pricing, modern equipment showcase, patient testimonials, news & blog, and online appointment booking. Fully responsive with smooth animations.',
    'projectsPage.project12.client': 'Nha Khoa ABC',
    'projectsPage.project13.title': 'Wrencoffee - Coffee Shop',
    'projectsPage.project13.category': 'Business Website',
    'projectsPage.project13.description': 'A modern, responsive website for a Vietnamese coffee shop featuring smooth scroll animations, interactive elements, parallax cards, dynamic navigation, and optimized performance with lazy loading images. Clean, sophisticated design with Vietnamese coffee aesthetics.',
    'projectsPage.project13.client': 'Wrencoffee',
    'projectsPage.project20.title': 'Psyche - AI Psychology Chatbot',
    'projectsPage.project20.category': 'AI Mental Health Application',
    'projectsPage.project20.description': 'An AI-powered psychologist chatbot delivering empathetic, evidence-based psychological guidance. Features RAG with 6 curated psychology research documents, MBTI personality-aware responses for all 16 types, real-time streaming, voice output via Web Speech API, and persistent chat history. Built with FastAPI, LangChain, ChromaDB, and Groq\'s Llama 3.3 70B model.',
    'projectsPage.project20.client': 'Personal Project',
    'projectsPage.project14.title': 'Wrencos - AI Beauty & Skincare Platform',
    'projectsPage.project14.category': 'Full-Stack E-commerce Platform',
    'projectsPage.project14.description': 'A comprehensive AI-powered e-commerce and customer engagement platform for the beauty and skincare industry. Features include AI dermatology expert powered by Google Gemini, live streaming, RAG-based chat support, email marketing, HR & finance management, VNPay payment integration, and native mobile apps for both admin and customers.',
    'projectsPage.project14.client': 'Wrencos Beauty',
    'projectsPage.project15.title': 'Track Nutrition - AI Nutrition Tracking Platform',
    'projectsPage.project15.category': 'Health & Wellness Application',
    'projectsPage.project15.description': 'An AI-powered multi-platform nutrition tracking system integrating 300,000+ USDA-verified foods, 500+ healthy recipes, and 200+ educational videos. Features Google Gemini AI for meal image analysis, natural language food parsing, intelligent health chatbot, and evidence-based recommendations. Built with React Native mobile app and responsive web interface.',
    'projectsPage.project15.client': 'Nutrition Solutions',
    'projectsPage.project16.title': 'Skin Study - AI Skin Health & Beauty Platform',
    'projectsPage.project16.category': 'Healthcare AI Application',
    'projectsPage.project16.description': 'An intelligent multi-platform application providing evidence-based, personalised skincare consultation through AI-assisted interfaces. Features Retrieval-Augmented Generation (RAG) with dermatology textbooks, Google Gemini AI for multi-modal analysis (text, image, voice), 8-factor skin analysis algorithm, multilingual support (10+ languages), and cross-platform apps (Vue.js web, React Native mobile).',
    'projectsPage.project16.client': 'Wrencos Beauty',
    'projectsPage.project17.title': 'Warehouse Management System',
    'projectsPage.project17.category': 'Enterprise Management System',
    'projectsPage.project17.description': 'A comprehensive warehouse and inventory management system built with Laravel. Features include real-time inventory tracking, stock movement management, multi-warehouse support, supplier management, reporting and analytics, and role-based access control. Designed for efficient warehouse operations with CRUD operations for products, categories, and inventory movements.',
    'projectsPage.project17.client': 'Enterprise Solution',
    'projectsPage.project18.title': 'Education Center Management System',
    'projectsPage.project18.category': 'Enterprise Management System',
    'projectsPage.project18.description': 'A robust education center management application designed to handle student enrollments, course scheduling, and academic administration. Built with .NET and SQL Server for secure and reliable performance.',
    'projectsPage.project18.client': 'Education Center',
    'projectsPage.project19.title': 'Books Application',
    'projectsPage.project19.category': 'Desktop & Web Application',
    'projectsPage.project19.description': 'A data structures and algorithms driven bookstore management system with admin and customer modules, CSV-based persistence, and a web interface deployment. Built in Java with custom ADTs and sorting/searching algorithms.',
    'projectsPage.project19.client': 'Academic Project',
    'projectsPage.project21.title': 'Bespoke Crystal Bracelets & Luxury Accessories',
    'projectsPage.project21.category': 'E-commerce & Customization Platform',
    'projectsPage.project21.description': 'A bespoke jewelry e-commerce platform that lets customers design their own crystal bracelets and luxury sunglasses with an interactive drag-and-drop builder. Built with React, Express, MongoDB, and Cloudinary for image management.',
    'projectsPage.project21.client': 'Personal Project',
    'projectsPage.client': 'Client',
    'projectsPage.year': 'Year',
    
    // About Page
    'aboutPage.title': 'About Wren Tech',
    'aboutPage.subtitle': 'We are a team of passionate developers and designers committed to creating exceptional digital experiences',
    'aboutPage.storyTitle': 'Our Story',
    'aboutPage.story1': 'Founded in 2025, Wren Tech emerged from a simple belief: every business deserves a powerful digital presence. What started as a small team of developers has grown into a full-service tech agency serving clients worldwide.',
    'aboutPage.story2': 'We specialize in creating modern, high-performance websites and applications using cutting-edge technologies. Our approach combines technical excellence with creative design to deliver solutions that not only look great but drive real business results.',
    'aboutPage.story3': 'With over 100 successful projects and counting, we pride ourselves on our commitment to quality, transparency, and client satisfaction.',
    'aboutPage.valuesTitle': 'Our Values',
    'aboutPage.value1.title': 'Quality First',
    'aboutPage.value1.description': 'We never compromise on quality. Every line of code, every design element is crafted with precision and care.',
    'aboutPage.value2.title': 'Client Success',
    'aboutPage.value2.description': 'Your success is our success. We\'re committed to delivering solutions that help your business grow and thrive.',
    'aboutPage.value3.title': 'Innovation',
    'aboutPage.value3.description': 'We stay ahead of technology trends to ensure your digital presence is always modern and competitive.',
    
    // Contact Page
    'contactPage.title': 'Get In Touch',
    'contactPage.subtitle': "Have a project in mind? Let's discuss how we can help bring your vision to life",
    'contactPage.formTitle': 'Send Us a Message',
    'contactPage.name': 'Full Name',
    'contactPage.email': 'Email Address',
    'contactPage.phone': 'Phone Number',
    'contactPage.service': 'Service Interested In',
    'contactPage.message': 'Your Message',
    'contactPage.selectService': 'Select a service',
    'contactPage.serviceWebDev': 'Web Development',
    'contactPage.serviceUiUx': 'UI/UX Design',
    'contactPage.serviceEcommerce': 'E-commerce Solutions',
    'contactPage.serviceBackend': 'Backend Development',
    'contactPage.serviceSeo': 'SEO Optimization',
    'contactPage.serviceOther': 'Other',
    'contactPage.messagePlaceholder': 'Tell us about your project...',
    'contactPage.sending': 'Sending...',
    'contactPage.send': 'Send Message',
    'contactPage.infoTitle': 'Contact Information',
    'contactPage.address': 'Address',
    'contactPage.addressValue': '75 Luong Huu Khanh, Son Tra, Danang, Vietnam',
    'contactPage.phoneValue': '+84 932 117 341',
    'contactPage.emailValue': 'info@wrentech.com',
    'contactPage.hoursTitle': 'Business Hours',
    'contactPage.monday': 'Monday - Friday',
    'contactPage.mondayHours': '7:00 AM - 7:00 PM',
    'contactPage.saturday': 'Saturday',
    'contactPage.saturdayHours': '7:00 AM - 4:00 PM',
    'contactPage.sunday': 'Sunday',
    'contactPage.sundayHours': 'Closed',
    'contactPage.successMessage': 'Thank you for your message! We will get back to you soon.',
    'contactPage.namePlaceholder': 'John Doe',
    'contactPage.emailPlaceholder': 'john@example.com',
    'contactPage.phonePlaceholder': '+84 987 654 321',
  },
  vi: {
    // Navigation
    'nav.home': 'Trang chủ',
    'nav.services': 'Dịch vụ',
    'nav.projects': 'Dự án',
    'nav.about': 'Về chúng tôi',
    'nav.contact': 'Liên hệ',
    'nav.getStarted': 'Bắt đầu',
    
    // Hero
    'hero.badge': 'Được tin tưởng bởi hơn 100 doanh nghiệp',
    'hero.title': 'Giải pháp Web Hiện Đại cho',
    'hero.titleHighlight': 'Doanh Nghiệp của Bạn',
    'hero.description': 'Chúng tôi tạo ra các trang web ấn tượng, ứng dụng web mạnh mẽ và sản phẩm kỹ thuật số cao cấp. Từ React đến Next.js, chúng tôi hiện thực hóa tầm nhìn kỹ thuật số của bạn.',
    'hero.cta1': 'Bắt đầu dự án',
    'hero.cta2': 'Xem các dự án',
    'hero.stat1': 'Dự án hoàn thành',
    'hero.stat2': 'Năm kinh nghiệm',
    'hero.stat3': 'Đánh giá',
    
    // Services
    'services.title': 'Dịch vụ của chúng tôi',
    'services.subtitle': 'Giải pháp kỹ thuật số toàn diện giúp doanh nghiệp phát triển và thành công trực tuyến',
    'services.viewAll': 'Xem tất cả dịch vụ',
    'service.webDev': 'Phát triển Website',
    'service.webDevDesc': 'Website tùy chỉnh được xây dựng với công nghệ hiện đại như React, Next.js và TypeScript để đạt hiệu suất tối ưu.',
    'service.uiux': 'Thiết kế UI/UX',
    'service.uiuxDesc': 'Giao diện đẹp mắt, trực quan mang lại trải nghiệm người dùng xuất sắc và thúc đẩy tương tác.',
    'service.ecommerce': 'Giải pháp Thương mại điện tử',
    'service.ecommerceDesc': 'Cửa hàng trực tuyến hoàn chỉnh với thanh toán an toàn, quản lý kho và trải nghiệm thanh toán liền mạch.',
    'service.backend': 'Phát triển Backend',
    'service.backendDesc': 'Giải pháp máy chủ mạnh mẽ với cơ sở dữ liệu, API và kiến trúc có khả năng mở rộng cho ứng dụng của bạn.',
    'service.responsive': 'Thiết kế Responsive',
    'service.responsiveDesc': 'Thiết kế mobile-first hoàn hảo trên mọi thiết bị, từ điện thoại thông minh đến máy tính để bàn.',
    'service.seo': 'Tối ưu hóa SEO',
    'service.seoDesc': 'Tối ưu hóa công cụ tìm kiếm để cải thiện khả năng hiển thị và thu hút lưu lượng truy cập tự nhiên.',
    
    // Projects
    'projects.title': 'Dự án nổi bật',
    'projects.subtitle': 'Khám phá danh mục các dự án thành công được thực hiện cho khách hàng trên toàn thế giới',
    'projects.viewAll': 'Xem tất cả dự án',
    
    // Testimonials
    'testimonials.title': 'Đánh giá từ khách hàng',
    'testimonials.subtitle': 'Phản hồi từ các doanh nghiệp đã tin tưởng và phát triển cùng chúng tôi',
    'testimonial1.name': 'Sarah Johnson',
    'testimonial1.role': 'CEO, TechStart Inc',
    'testimonial1.content': 'Làm việc với Wren Tech là một trải nghiệm tuyệt vời. Họ đã bàn giao nền tảng thương mại điện tử trước thời hạn với chất lượng đặc biệt. Sự chú ý đến chi tiết và giao tiếp trong suốt dự án rất xuất sắc.',
    'testimonial2.name': 'Michael Chen',
    'testimonial2.role': 'Người sáng lập, CloudSolutions',
    'testimonial2.content': 'Đội ngũ đã biến website lỗi thời của chúng tôi thành một ứng dụng hiện đại, hiệu suất cao. Tỷ lệ chuyển đổi tăng 150% trong tháng đầu tiên. Rất khuyến khích cho bất kỳ doanh nghiệp nào muốn mở rộng quy mô.',
    'testimonial3.name': 'Emily Rodriguez',
    'testimonial3.role': 'Giám đốc Marketing, GrowthLab',
    'testimonial3.content': 'Điều ấn tượng nhất là khả năng hiểu nhu cầu kinh doanh của chúng tôi và chuyển thành một website đẹp, chức năng. Dự án hoàn thành đúng hạn và trong ngân sách.',
    'testimonial4.name': 'David Park',
    'testimonial4.role': 'Chủ nhà hàng, Urban Bistro',
    'testimonial4.content': 'Hệ thống đặt bàn online đã giúp nhà hàng tôi tăng trưởng mạnh mẽ. Khách hàng rất thích giao diện dễ sử dụng và số lượng đặt bàn tăng đáng kể. Đội ngũ làm việc rất chuyên nghiệp.',
    'testimonial5.name': 'Lisa Thompson',
    'testimonial5.role': 'Nhà thiết kế tự do',
    'testimonial5.content': 'Là freelancer, tôi cần một portfolio chuyên nghiệp. Wren Tech đã tạo ra chính xác những gì tôi mong muốn và còn hơn thế nữa. Tôi nhận được nhiều lời khen và dự án mới nhờ website này.',
    'testimonial6.name': 'James Wilson',
    'testimonial6.role': 'Giám đốc, FitLife Gym',
    'testimonial6.content': 'Ứng dụng fitness họ phát triển cho chúng tôi rất thành công. Hội viên thích theo dõi tiến độ và nó giúp xây dựng cộng đồng mạnh mẽ hơn. Dịch vụ chuyên nghiệp từ đầu đến cuối.',
    
    // CTA
    'cta.title': 'Sẵn sàng tạo ra điều gì đó tuyệt vời?',
    'cta.subtitle': 'Hãy thảo luận về dự án của bạn và tạo ra giải pháp kỹ thuật số mang lại kết quả cho doanh nghiệp.',
    'cta.button1': 'Bắt đầu ngay hôm nay',
    'cta.button2': 'Gửi email',
    'cta.support': 'Hỗ trợ',
    'cta.satisfaction': 'Đảm bảo hài lòng',
    'cta.delivery': 'Giao hàng nhanh',
    
    // Footer
    'footer.description': 'Phát triển website chuyên nghiệp và giải pháp số. Xây dựng website hiện đại và ứng dụng web cho doanh nghiệp trên toàn thế giới.',
    'footer.services': 'Dịch vụ',
    'footer.company': 'Công ty',
    'footer.contact': 'Liên hệ',
    'footer.rights': 'Bảo lưu mọi quyền.',
    'footer.service1': 'Phát triển Website',
    'footer.service2': 'Ứng dụng React',
    'footer.service3': 'Giải pháp Thương mại điện tử',
    'footer.service4': 'Sản phẩm kỹ thuật số',
    'footer.aboutUs': 'Về chúng tôi',
    
    // Services Page
    'servicesPage.title': 'Dịch vụ của chúng tôi',
    'servicesPage.subtitle': 'Giải pháp kỹ thuật số toàn diện được thiết kế để giúp doanh nghiệp phát triển và thành công trên web hiện đại',
    'servicesPage.cta.title': 'Sẵn sàng bắt đầu?',
    'servicesPage.cta.subtitle': 'Hãy thảo luận về dự án của bạn và tạo ra giải pháp phù hợp với nhu cầu của bạn',
    'servicesPage.cta.button': 'Liên hệ ngay hôm nay',
    'servicesPage.feature1': 'Phát triển tùy chỉnh',
    'servicesPage.feature2': 'Thiết kế Responsive',
    'servicesPage.feature3': 'Tối ưu hóa hiệu suất',
    'servicesPage.feature4': 'Thân thiện với SEO',
    'servicesPage.feature5': 'Nghiên cứu người dùng',
    'servicesPage.feature6': 'Wireframing',
    'servicesPage.feature7': 'Prototyping',
    'servicesPage.feature8': 'Thiết kế trực quan',
    'servicesPage.feature9': 'Giỏ hàng',
    'servicesPage.feature10': 'Tích hợp thanh toán',
    'servicesPage.feature11': 'Quản lý sản phẩm',
    'servicesPage.feature12': 'Theo dõi đơn hàng',
    'servicesPage.feature13': 'Phát triển API',
    'servicesPage.feature14': 'Thiết kế cơ sở dữ liệu',
    'servicesPage.feature15': 'Xác thực',
    'servicesPage.feature16': 'Tích hợp Cloud',
    'servicesPage.feature17': 'Mobile-First',
    'servicesPage.feature18': 'Cross-Browser',
    'servicesPage.feature19': 'Progressive Web Apps',
    'servicesPage.feature20': 'Tối ưu hóa cảm ứng',
    'servicesPage.feature21': 'Nghiên cứu từ khóa',
    'servicesPage.feature22': 'On-Page SEO',
    'servicesPage.feature23': 'Technical SEO',
    'servicesPage.feature24': 'Phân tích',
    
    // Projects Page
    'projectsPage.title': 'Dự án của chúng tôi',
    'projectsPage.subtitle': 'Khám phá danh mục các dự án thành công được thực hiện cho khách hàng trên toàn thế giới',
    'projectsPage.project7.title': 'Website Paradise Resort',
    'projectsPage.project7.category': 'Phát triển Web',
    'projectsPage.project7.description': 'Website resort cao cấp hiện đại với hệ thống đặt phòng, danh sách phòng, thư viện tương tác và thông tin ẩm thực. Được xây dựng bằng Next.js và Prisma để mang đến trải nghiệm người dùng hoàn hảo.',
    'projectsPage.project7.client': 'Paradise Resort',
    'projectsPage.project8.title': 'Cửa hàng Thời trang Online',
    'projectsPage.project8.category': 'Thương mại điện tử',
    'projectsPage.project8.description': 'Nền tảng thương mại điện tử thời trang hiện đại với danh mục sản phẩm, danh sách yêu thích, giỏ hàng, chuyển đổi tiền tệ và tính năng so sánh sản phẩm. Được xây dựng bằng React, TypeScript và Vite để đạt hiệu suất tối ưu.',
    'projectsPage.project8.client': 'Fashion Boutique',
    'projectsPage.project9.title': 'Nền tảng Bất động sản',
    'projectsPage.project9.category': 'Ứng dụng Web',
    'projectsPage.project9.description': 'Website bất động sản toàn diện với danh sách bất động sản, bộ lọc tìm kiếm nâng cao, bản đồ Mapbox tương tác, hệ thống yêu thích và xác thực người dùng. Được xây dựng bằng Next.js 14 và PostgreSQL để đạt hiệu suất tối ưu.',
    'projectsPage.project9.client': 'Prime Properties',
    'projectsPage.project10.title': 'Urban Bistro - Đặt bàn Nhà hàng',
    'projectsPage.project10.category': 'Ứng dụng Web Full-Stack',
    'projectsPage.project10.description': 'Hệ thống đặt bàn nhà hàng full-stack với cập nhật tình trạng sẵn có theo thời gian thực, quản lý thực đơn, đặt bàn và xác nhận email tự động. Tích hợp Socket.io cho cập nhật trực tiếp và Redis caching.',
    'projectsPage.project10.client': 'Urban Bistro',
    'projectsPage.project11.title': 'Car Dana - Đại lý Ô tô',
    'projectsPage.project11.category': 'Website Doanh nghiệp',
    'projectsPage.project11.description': 'Website đại lý ô tô chuyên nghiệp với hero slider, danh sách xe với giá cả, ưu đãi đặc biệt, tin tức & sự kiện, thư viện ảnh khách hàng, đánh giá và form liên hệ. Thiết kế responsive với hiệu ứng mượt mà và nút floating.',
    'projectsPage.project11.client': 'Car Dana',
    'projectsPage.project12.title': 'Nha Khoa ABC - Phòng khám Nha khoa',
    'projectsPage.project12.category': 'Website Y tế',
    'projectsPage.project12.description': 'Website phòng khám nha khoa chuyên nghiệp với danh sách dịch vụ, hồ sơ bác sĩ, bảng giá minh bạch, trưng bày thiết bị hiện đại, đánh giá bệnh nhân, tin tức & blog và đặt lịch hẹn trực tuyến. Thiết kế responsive với hiệu ứng mượt mà.',
    'projectsPage.project12.client': 'Nha Khoa ABC',
    'projectsPage.project13.title': 'Wrencoffee - Quán Cà phê',
    'projectsPage.project13.category': 'Website Doanh nghiệp',
    'projectsPage.project13.description': 'Website hiện đại, responsive cho quán cà phê Việt Nam với hiệu ứng cuộn mượt mà, các yếu tố tương tác, thẻ parallax, điều hướng động và hiệu suất tối ưu với lazy loading hình ảnh. Thiết kế tinh tế, sạch sẽ với phong cách cà phê Việt Nam.',
    'projectsPage.project13.client': 'Wrencoffee',
    'projectsPage.project20.title': 'Psyche - Chatbot Tâm lý AI',
    'projectsPage.project20.category': 'Ứng dụng AI Sức khỏe Tâm thần',
    'projectsPage.project20.description': 'Chatbot tâm lý AI cung cấp hướng dẫn tâm lý đồng cảm, dựa trên bằng chứng khoa học. Tích hợp RAG với 6 tài liệu nghiên cứu tâm lý học được tuyển chọn, phản hồi nhận biết tính cách MBTI cho cả 16 loại, phát trực tiếp theo thời gian thực, đầu ra giọng nói qua Web Speech API và lịch sử trò chuyện liên tục. Được xây dựng bằng FastAPI, LangChain, ChromaDB và mô hình Llama 3.3 70B của Groq.',
    'projectsPage.project20.client': 'Dự án Cá nhân',
    'projectsPage.project14.title': 'Wrencos - Nền tảng Làm đẹp & Chăm sóc da AI',
    'projectsPage.project14.category': 'Nền tảng Thương mại điện tử Full-Stack',
    'projectsPage.project14.description': 'Nền tảng thương mại điện tử và tương tác khách hàng AI toàn diện cho ngành làm đẹp và chăm sóc da. Tính năng bao gồm chuyên gia da liễu AI được hỗ trợ bởi Google Gemini, phát trực tiếp, hỗ trợ chat dựa trên RAG, email marketing, quản lý nhân sự & tài chính, tích hợp thanh toán VNPay và ứng dụng di động native cho cả admin và khách hàng.',
    'projectsPage.project14.client': 'Wrencos Beauty',
    'projectsPage.project15.title': 'Track Nutrition - Nền tảng Theo dõi Dinh dưỡng AI',
    'projectsPage.project15.category': 'Ứng dụng Sức khỏe & Wellness',
    'projectsPage.project15.description': 'Hệ thống theo dõi dinh dưỡng đa nền tảng được hỗ trợ bởi AI, tích hợp hơn 300,000 thực phẩm được USDA xác minh, hơn 500 công thức nấu ăn lành mạnh và hơn 200 video giáo dục. Tính năng bao gồm phân tích hình ảnh bữa ăn bằng Google Gemini AI, xử lý ngôn ngữ tự nhiên cho thực phẩm, chatbot sức khỏe thông minh và đề xuất dựa trên bằng chứng khoa học. Được xây dựng với ứng dụng di động React Native và giao diện web responsive.',
    'projectsPage.project15.client': 'Nutrition Solutions',
    'projectsPage.project16.title': 'Skin Study - Nền tảng Sức khỏe Da & Làm đẹp AI',
    'projectsPage.project16.category': 'Ứng dụng AI Y tế',
    'projectsPage.project16.description': 'Ứng dụng đa nền tảng thông minh cung cấp tư vấn chăm sóc da cá nhân hóa dựa trên bằng chứng khoa học thông qua giao diện hỗ trợ AI. Tính năng bao gồm Retrieval-Augmented Generation (RAG) với sách giáo khoa da liễu, Google Gemini AI cho phân tích đa phương thức (văn bản, hình ảnh, giọng nói), thuật toán phân tích da 8 yếu tố, hỗ trợ đa ngôn ngữ (10+ ngôn ngữ) và ứng dụng đa nền tảng (Vue.js web, React Native mobile).',
    'projectsPage.project16.client': 'Wrencos Beauty',
    'projectsPage.project17.title': 'Hệ thống Quản lý Kho',
    'projectsPage.project17.category': 'Hệ thống Quản lý Doanh nghiệp',
    'projectsPage.project17.description': 'Hệ thống quản lý kho và tồn kho toàn diện được xây dựng bằng Laravel. Tính năng bao gồm theo dõi tồn kho thời gian thực, quản lý di chuyển hàng hóa, hỗ trợ đa kho, quản lý nhà cung cấp, báo cáo và phân tích, và kiểm soát truy cập dựa trên vai trò. Được thiết kế cho hoạt động kho hàng hiệu quả với các thao tác CRUD cho sản phẩm, danh mục và di chuyển tồn kho.',
    'projectsPage.project17.client': 'Giải pháp Doanh nghiệp',
    'projectsPage.project18.title': 'Hệ thống Quản lý Trung tâm Giáo dục',
    'projectsPage.project18.category': 'Hệ thống Quản lý Doanh nghiệp',
    'projectsPage.project18.description': 'Ứng dụng quản lý trung tâm giáo dục mạnh mẽ được thiết kế để xử lý ghi danh học viên, xếp lịch học và quản trị học thuật. Được xây dựng bằng .NET và SQL Server để mang lại hiệu suất an toàn và đáng tin cậy.',
    'projectsPage.project18.client': 'Trung tâm Giáo dục',
    'projectsPage.project19.title': 'Books Application',
    'projectsPage.project19.category': 'Ứng dụng Desktop & Web',
    'projectsPage.project19.description': 'Hệ thống quản lý cửa hàng sách ứng dụng cấu trúc dữ liệu và giải thuật với các module quản trị và khách hàng, lưu trữ dữ liệu bằng CSV, đồng thời triển khai giao diện web. Được xây dựng bằng Java với ADT tự cài đặt và các thuật toán sắp xếp/tìm kiếm.',
    'projectsPage.project19.client': 'Đồ án học thuật',
    'projectsPage.project21.title': 'Vòng tay Pha lê & Phụ kiện Xa xỉ Thiết kế riêng',
    'projectsPage.project21.category': 'Nền tảng Thương mại điện tử & Tùy chỉnh',
    'projectsPage.project21.description': 'Nền tảng thương mại điện tử trang sức cho phép khách hàng tự thiết kế vòng tay pha lê và kính mát xa xỉ của riêng mình với công cụ kéo-thả tương tác. Được xây dựng bằng React, Express, MongoDB và Cloudinary để quản lý hình ảnh.',
    'projectsPage.project21.client': 'Dự án Cá nhân',
    'projectsPage.client': 'Khách hàng',
    'projectsPage.year': 'Năm',
    
    // About Page
    'aboutPage.title': 'Về Wren Tech',
    'aboutPage.subtitle': 'Chúng tôi là đội ngũ các nhà phát triển và thiết kế đam mê, cam kết tạo ra trải nghiệm kỹ thuật số đặc biệt',
    'aboutPage.storyTitle': 'Câu chuyện của chúng tôi',
    'aboutPage.story1': 'Được thành lập vào năm 2020, Wren Tech xuất hiện từ một niềm tin đơn giản: mọi doanh nghiệp đều xứng đáng có một sự hiện diện kỹ thuật số mạnh mẽ. Những gì bắt đầu từ một nhóm nhỏ các nhà phát triển đã phát triển thành một công ty công nghệ dịch vụ đầy đủ phục vụ khách hàng trên toàn thế giới.',
    'aboutPage.story2': 'Chúng tôi chuyên tạo ra các trang web và ứng dụng hiện đại, hiệu suất cao bằng cách sử dụng các công nghệ tiên tiến như React, Next.js và TypeScript. Phương pháp của chúng tôi kết hợp sự xuất sắc về kỹ thuật với thiết kế sáng tạo để cung cấp các giải pháp không chỉ trông đẹp mà còn mang lại kết quả kinh doanh thực sự.',
    'aboutPage.story3': 'Với hơn 100 dự án thành công và đang tiếp tục, chúng tôi tự hào về cam kết của mình đối với chất lượng, minh bạch và sự hài lòng của khách hàng.',
    'aboutPage.valuesTitle': 'Giá trị của chúng tôi',
    'aboutPage.value1.title': 'Chất lượng là hàng đầu',
    'aboutPage.value1.description': 'Chúng tôi không bao giờ thỏa hiệp về chất lượng. Mỗi dòng mã, mỗi yếu tố thiết kế đều được tạo ra với độ chính xác và sự cẩn thận.',
    'aboutPage.value2.title': 'Thành công của khách hàng',
    'aboutPage.value2.description': 'Thành công của bạn là thành công của chúng tôi. Chúng tôi cam kết cung cấp các giải pháp giúp doanh nghiệp của bạn phát triển và thịnh vượng.',
    'aboutPage.value3.title': 'Đổi mới',
    'aboutPage.value3.description': 'Chúng tôi luôn đi đầu trong xu hướng công nghệ để đảm bảo sự hiện diện kỹ thuật số của bạn luôn hiện đại và cạnh tranh.',
    
    // Contact Page
    'contactPage.title': 'Liên hệ với chúng tôi',
    'contactPage.subtitle': 'Bạn có dự án trong đầu? Hãy thảo luận về cách chúng tôi có thể giúp hiện thực hóa tầm nhìn của bạn',
    'contactPage.formTitle': 'Gửi tin nhắn cho chúng tôi',
    'contactPage.name': 'Họ và tên',
    'contactPage.email': 'Địa chỉ Email',
    'contactPage.phone': 'Số điện thoại',
    'contactPage.service': 'Dịch vụ quan tâm',
    'contactPage.message': 'Tin nhắn của bạn',
    'contactPage.selectService': 'Chọn dịch vụ',
    'contactPage.serviceWebDev': 'Phát triển Website',
    'contactPage.serviceUiUx': 'Thiết kế UI/UX',
    'contactPage.serviceEcommerce': 'Giải pháp Thương mại điện tử',
    'contactPage.serviceBackend': 'Phát triển Backend',
    'contactPage.serviceSeo': 'Tối ưu hóa SEO',
    'contactPage.serviceOther': 'Khác',
    'contactPage.messagePlaceholder': 'Hãy cho chúng tôi biết về dự án của bạn...',
    'contactPage.sending': 'Đang gửi...',
    'contactPage.send': 'Gửi tin nhắn',
    'contactPage.infoTitle': 'Thông tin liên hệ',
    'contactPage.address': 'Địa chỉ',
    'contactPage.addressValue': '75 75 Luong Huu Khanh, Son Tra, Danang, Vietnam',
    'contactPage.phoneValue': '+84 932 117 341',
    'contactPage.emailValue': 'info@wrentech.com',
    'contactPage.hoursTitle': 'Giờ làm việc',
    'contactPage.monday': 'Thứ Hai - Thứ Sáu',
    'contactPage.mondayHours': '9:00 AM - 6:00 PM',
    'contactPage.saturday': 'Thứ Bảy',
    'contactPage.saturdayHours': '10:00 AM - 4:00 PM',
    'contactPage.sunday': 'Chủ Nhật',
    'contactPage.sundayHours': 'Đóng cửa',
    'contactPage.successMessage': 'Cảm ơn bạn đã gửi tin nhắn! Chúng tôi sẽ liên hệ lại với bạn sớm.',
    'contactPage.namePlaceholder': 'Nguyễn Văn A',
    'contactPage.emailPlaceholder': 'nguyenvana@example.com',
    'contactPage.phonePlaceholder': '+84 123 456 789',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
